config/routes.rb
Rails.application.routes.draw do


  

  devise_for :providers, controllers: {
    sessions: 'providers/sessions',
    passwords: 'providers/passwords',
    registrations: 'providers/registrations',
    invitations: 'providers/invitations'
  }
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        invitations: 'users/invitations'
      }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get 'registrations/:id/edit_password', to: 'registrations#edit_password', as: 'edit_password'
    put 'registrations/:id/update_password', to: 'registrations#update_password', as: 'update_password'
  end

  devise_scope :provider do
    get '/providers/sign_out' => 'devise/sessions#destroy'
  end

    
  root "tops#index"
  get "tops/index",to:"tops#index"
  get "tops/news",to:"tops#news"
  get "tops/news/:id",to:"tops#newsshow"
  get "tops/policy",to:"tops#policy"
  get "tops/terms",to:"tops#terms"
  get "tops/addprovidercomp",to:"tops#addprovidercomp"
  get "tops/destroycomp",to: "tops#destroycomp"

  resources :works do
    member do
      get :move_top
      get :move_higher
      get :move_lower
      get :move_bottom
    end
    resources :introductions, only: [:create, :edit, :update]
    resources :details, only: [:create]
    resources :work_providers, only: [:create]
  end


  resources :news
  resources :questions
  

  get "posts/index",to:"posts#index"
  get "posts/:id",to:"posts#show"
  get "works/:id/introductions/new", to:"introductions#new"
  get "works/:id/introductions/edit", to:"introductions#edit"
  get "works/:id/work_providers/index", to:"work_providers#index"
  get "works/:id/work_providers/new", to:"work_providers#new"
  post "works/:id/work_providers", to:"work_providers#create"
  get "introductions/complete", to:"introductions#complete"

  get "works/:id/details/new", to:"details#new"

  resources :details

  get "works/:id/introductions", to:"introductions#index"
  get "works/:id/introductions/:id", to:"introductions#show"




  get "introductions/index", to:"introductions#index"
  get "introductions/:id", to:"introductions#show"
  get "introductions/:id/edit", to:"introductions#edit"

  

 resources :introductions do
    resources :progresses, only: [:create, :edit, :update, :show]
  end
  get "introductions/:id/progresses",to:"progresses#new"
  get "progresses/index",to:"progresses#index"
  get "progresses/:id",to:"progresses#show"
  get "progresses/news",to:"progresses#news"

  get "users/index",to:"users#index"
  get "users/:id",to:"users#show"
  
  get "users/complete/:id",to:"users#complete"
  get "users/mypage/:id",to:"users#mypage"
  get "users/destroy/:id",to:"users#destroy"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/news.rb
class News < ApplicationRecord



  def self.search(search)
      return News.all unless search
      News.where(['title LIKE ?', "%#{search}%"])
    end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :authenticate_provider!,only: [:index,:show,:edit,:update]
  before_action :set_news, only: %i[ show edit update destroy ]

  # GET /news or /news.json
  def index
    @news = News.all.page(params[:page]).per(10)
    @newsnew = News.new
    @q = News.ransack(params[:q])
    @news = @q.result(distinct: true).page(params[:page]).order("created_at desc")
    @introductionnumber = current_provider.works.joins(:introductions).where(introductions: {step: nil}).count
    @introductionall = Introduction.where(step: nil).count
    @detailnumber = current_provider.works.joins(:details).where(details: {status: "未対応"}).count
    @detailnumberall = Detail.where(status: "未対応").count
  end


  # GET /news/1 or /news/1.json
  def show
    @news = News.find(params[:id])
    @introductionnumber = current_provider.works.joins(:introductions).where(introductions: {step: nil}).count
    @introductionall = Introduction.where(step: nil).count
    @detailnumber = current_provider.works.joins(:details).where(details: {status: "未対応"}).count
    @detailnumberall = Detail.where(status: "未対応").count
  end

  # GET /news/new
  def new
    @news = News.new
    
    @introductionnumber = Introduction.all.count
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news or /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: "News was successfully created." }
        format.json { render :index, status: :created, location: @news }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1 or /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: "News was successfully updated." }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1 or /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: "News was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    #Viewのformで取得したパラメータをモデルに渡す
    @news = News.search(params[:search])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def news_params
      params.require(:news).permit(:title, :content)
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
<%= form_with(model: @news, local: true) do |form| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
        <% @news.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="formSet">
    <%= form.label :タイトル %>
    <%= form.text_field :title %>
  </div>

  <div class="formSet">
    <%= form.label :内容 %>
    <%= form.text_area :content, autofocus: true,size: "40x10" %>
  </div>

  <div class="actions">
    <%= form.submit "作成する",class:"button" %>
  </div>
<% end %>

</div>
</div>

app/views/news/edit.html.erb
<h1>お知らせを編集する</h1>

<%= render 'form', news: @news %>

<div class="toTop">
<%= link_to '削除', @news, method: :delete,class:"deletebtn", data: { confirm: 'Are you sure?' } %>
<%= link_to '一覧に戻る', news_index_path %>
</div>

app/views/news/index.html.erb
<body class="providerPage">
  <div class="side">
    <%= render '/works/side' %>
  </div>
 
  <div class="main">
    
  <%= render '/works/side_header' %>
    
        
    <div class="userIndex">
      <h1 class="text-left">お知らせ</h1>
      <div class="providerTable">
     

        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary toNew" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
          ＋ 新規作成
        </button>

        <!-- Modal -->
        <div class="modal w-75 m-auto" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title h4" id="staticBackdropLabel">新規お知らせ作成</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">

              <%= form_with(model: @newsnew, local: true) do |form| %>
              <% if @newsnew.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@newsnew.errors.count, "error") %> prohibited this news from being saved:</h2>

                  <ul>
                    <% @newsnew.errors.each do |error| %>
                      <li><%= error.full_message %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>

              <div class="w-75 m-auto mb-4 mt-2">
                <%= form.label :タイトル,class:"h4" %>
                <%= form.text_field :title,class:"form-control",id:"exampleFormControlInput1" %>
              </div>

              <div class="w-75 m-auto mb-4">
                <%= form.label :内容,class:"h4" %>
                <%= form.text_area :content,class:"form-control ",id:"exampleFormControlTextarea1", size: "20x10" %>
                
              </div>

                
              
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">閉じる</button>
                <%= form.submit "作成する",class:"btn btn-primary",data: { confirm:"作成しますか？"} %>    
                <% end %>
              </div>
              </div>
            </div>
          </div>
        </div>




      <div class="search-form">
        <%= search_form_for @q, url: news_index_path do |f| %>
            <%= f.label :title, "キーワード",class:"fs-4 " %>
            <%= f.search_field :title_cont,class:"fs-4 rounded border border-dark" %>

            <%= f.submit "検索",id:"btn",class:"fs-4 " %>
        <% end %>
      </div>

        <table class="table userTable ">
          <thead class="heading border">
            <tr class="text-left border">
              <th class=" ">タイトル</th>
              <th class="">作成日</th>
              <th class=" "></th>
            </tr>
          </thead>

          <tbody>
            <% @news.each do |news| %>
              <tr class="text-left">
                <td class="border "><%= news.title %></td>
                <td class="border "><%= news.created_at.strftime('%Y年%m月%d日') %></td>
                <td class="border text-center"><%= link_to '詳細', news,class:"toShow py-1 px-3 text-decoration-none" %></td>
                
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="text-center pagenation">
        <%= paginate @news %>
        </div>
        </div>
      </div>

  </div>
</body>

app/views/news/new.html.erb
<body class="providerPage">
  <div class="side">
    <%= render '/works/side' %>
  </div>
 
  <div class="main">
    <div class="mainHeader">
    <ul>
    <% if provider_signed_in? %>
      <li class=""><span><%= link_to '事業者ログアウト' , destroy_provider_session_path, method: :delete,data: { confirm: 'ログアウトしますか？' } %></span></li> 
      <li><%= current_provider.email %></li>
      <% else %>
      <li class=""><span>ログアウト</span></li> 
      <li>管理者名</li>
    
      <% end %>

    </ul>
    </div>
    
        
    <div class="userIndex">
    <h3 class="text-center">お知らせを作成する</h3>
      

       
        <%= render 'form', news: @news %>

<%= link_to '一覧に戻る', news_index_path %>

      </div>

  </div>
</body>

app/views/news/show.html.erb
<body class="providerPage">
  <div class="side">
    <%= render '/works/side' %>
  </div>
 
  <div class="main">
    
  <%= render '/works/side_header' %>
    
        
    <div class="userIndex">
    
      <h3 class="text-left">お知らせ</h3>
      <div class="providerTable ">
        <div>
          <%= link_to '削除する', @news, method: :delete,class:"btn btn-primary toNew", data: { confirm: '本当に削除しますか?' } %>
                <button type="button" class="btn btn-primary toNew" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
           編集する
        </button>
        </div>
      <div class="w-75 m-auto">
          <p class="border-bottom pb-3 text-left fw-bold fs-3 pt-3">
            <%= @news.title %>
          </p>

          <p>
            <%= auto_link(simple_format(@news.content), html: {target: '_blank'}) %>
          </p>
          </div>

      
       
          
          

        <!-- Modal -->
        <div class="modal w-75 m-auto" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title h4" id="staticBackdropLabel">新規お知らせ作成</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">

              <%= form_with(model: @news, url: news_path, local: true) do |form| %>
              <% if @news.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

                  <ul>
                    <% @news.errors.each do |error| %>
                      <li><%= error.full_message %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>

              <div class="w-75 m-auto mb-4 mt-2">
                <%= form.label :タイトル,class:"h4" %>
                <%= form.text_field :title,class:"form-control",id:"exampleFormControlInput1" %>
              </div>

              <div class="w-75 m-auto mb-4">
                <%= form.label :内容,class:"h4" %>
                <%= form.text_area :content,class:"form-control ",id:"exampleFormControlTextarea1", size: "20x10" %>
                
              </div>

                
              
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">閉じる</button>
                <%= form.submit "更新する",data: { confirm: '更新しますか？'},class:"btn btn-primary" %>    
                <% end %>
              </div>
              </div>
            </div>
          </div>
        </div>



          
        </div>
      </div>

  </div>
</body>