config/routes.rb
Rails.application.routes.draw do


  

  devise_for :providers, controllers: {
    sessions: 'providers/sessions',
    passwords: 'providers/passwords',
    registrations: 'providers/registrations',
    invitations: 'providers/invitations'
  }
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        invitations: 'users/invitations'
      }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get 'registrations/:id/edit_password', to: 'registrations#edit_password', as: 'edit_password'
    put 'registrations/:id/update_password', to: 'registrations#update_password', as: 'update_password'
  end

  devise_scope :provider do
    get '/providers/sign_out' => 'devise/sessions#destroy'
  end

    
  root "tops#index"
  get "tops/index",to:"tops#index"
  get "tops/news",to:"tops#news"
  get "tops/news/:id",to:"tops#newsshow"
  get "tops/policy",to:"tops#policy"
  get "tops/terms",to:"tops#terms"
  get "tops/addprovidercomp",to:"tops#addprovidercomp"
  get "tops/destroycomp",to: "tops#destroycomp"

  resources :works do
    member do
      get :move_top
      get :move_higher
      get :move_lower
      get :move_bottom
    end
    resources :introductions, only: [:create, :edit, :update]
    resources :details, only: [:create]
    resources :work_providers, only: [:create]
  end


  resources :news
  resources :questions
  

  get "posts/index",to:"posts#index"
  get "posts/:id",to:"posts#show"
  get "works/:id/introductions/new", to:"introductions#new"
  get "works/:id/introductions/edit", to:"introductions#edit"
  get "works/:id/work_providers/index", to:"work_providers#index"
  get "works/:id/work_providers/new", to:"work_providers#new"
  post "works/:id/work_providers", to:"work_providers#create"
  get "introductions/complete", to:"introductions#complete"

  get "works/:id/details/new", to:"details#new"

  resources :details

  get "works/:id/introductions", to:"introductions#index"
  get "works/:id/introductions/:id", to:"introductions#show"




  get "introductions/index", to:"introductions#index"
  get "introductions/:id", to:"introductions#show"
  get "introductions/:id/edit", to:"introductions#edit"

  

 resources :introductions do
    resources :progresses, only: [:create, :edit, :update, :show]
  end
  get "introductions/:id/progresses",to:"progresses#new"
  get "progresses/index",to:"progresses#index"
  get "progresses/:id",to:"progresses#show"
  get "progresses/news",to:"progresses#news"

  get "users/index",to:"users#index"
  get "users/:id",to:"users#show"
  
  get "users/complete/:id",to:"users#complete"
  get "users/mypage/:id",to:"users#mypage"
  get "users/destroy/:id",to:"users#destroy"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/introduction.rb
class Introduction < ApplicationRecord
  belongs_to :work, optional: true, foreign_key: "work_id"
  belongs_to :user, optional: true, foreign_key: "user_id"
  validates:user_id, {presence: true}

has_one    :master,  through: :child 

validates :name, presence: { message: "が入力されていません" }
validates :phonenumber, presence: { message: "が入力されていません" }
validates :permission, presence: { message: "にチェックを入れてください" }

  def self.search(search)
      return Introduction.all unless search
      Introduction.where(['name LIKE ?', "%#{search}%"])
    end
end

app/controllers/introductions_controller.rb
class IntroductionsController < ApplicationController
before_action :authenticate_provider!,only: [:index,:show,:edit,:update]
before_action :authenticate_user!,only: [:new,:create]

  def index
    @introductions = Introduction.all.page(params[:page]).per(10).order(id: :DESC)
    @q = Introduction.all.ransack(params[:q])
    @introductions = @q.result.page(params[:page]).per(10).order("created_at desc")
    @introductionnumber = current_provider.works.joins(:introductions).where(introductions: {step: nil}).count
    @introductionall = Introduction.where(step: nil).count
    @detailnumber = current_provider.works.joins(:details).where(details: {status: "未対応"}).count
    @detailnumberall = Detail.where(status: "未対応").count
    
  end

  def show
    @introduction = Introduction.find(params[:id])
    @introductionnumber = current_provider.works.joins(:introductions).where(introductions: {step: nil}).count
    @introductionall = Introduction.where(step: nil).count
    @detailnumber = current_provider.works.joins(:details).where(details: {status: "未対応"}).count
    @detailnumberall = Detail.where(status: "未対応").count
  end

 

  def new
     @work = Work.find(params[:id])
     @introduction = Introduction.new
  end

   

   def create
      @work = Work.find(params[:work_id])
      @introduction = Introduction.new(
        introduction_params ) #provider=事業者 #work=案件undefined method `email' for nil:NilClass
      
  
      
      if  @introduction.save
          IntroductionMailer.complete_introduction(@introduction,@work,@current_user ).deliver
          redirect_to introductions_complete_path
      else
          render :new  #同上
      end
    end
  
 

  
  def edit
    @introduction = Introduction.find(params[:id])
  end

  def update
    @introduction = Introduction.find(params[:id])
   
  if @introduction.update(
      update_introduction_params
    )
    
      redirect_to introduction_path
    else
      redirect_back(fallback_location: works_path)
    end
   
  
  end

  def search
    #Viewのformで取得したパラメータをモデルに渡す
    @introduction = Introduction.search(params[:introduction][:search])
  end

  
  def complete

  end
    

   private

  def introduction_params

    params.require(:introduction).permit(:name, :phonenumber, :contents, :step, :work_id, :id, :permission).merge(user_id: current_user.id, work_id: params[:work_id]) #ストロングパラメーターで、
  end 



  def update_introduction_params

    params.require(:introduction).permit(:step, :comment) #ストロングパラメーターで、
  end 
  



  
  

  

end

app/helpers/introductions_helper.rb
module IntroductionsHelper
end

app/views/introductions/complete.html.erb
<body class="complete">
<script type="text/javascript" src="https://js.felmat.net/fmcv.js?adid=A5768O&uqid=TIMESTAMP"></script>
  <div class="completeArea">
    <div class="logo">
    <%= image_tag "logo.jpg",class:"completeLogo" %>
    </div>

    <div>
    <h1 class="complete text-center">送信完了しました！</h1>
    <p class="text-center">この度はパラキャリをご利用いただきまして、誠にありがとうございます。</p>
    <p class="text-center">ご入力いただいた情報は無事に送信されました。</p>
    </div>

    <div class="toTop">
    <%= link_to "< マイページに戻る", "/users/mypage/#{ current_user.id }",class:"button" %>
    </div>
  </div>
</body>

app/views/introductions/edit.html.erb
 <%= form_with(model: [@introduction], local: true ) do |form| %>

 
  
  <div class="field">
    <%= form.label :口コミ進捗度,class: 'label'  %>

    <%= form.label :進行中,class: 'label'  %>
    <%= form.radio_button :step, '進行中' %>
    
    <%= form.label :断られました,class: 'label'  %>
    <%= form.radio_button :step, '断られました' %>

    <%= form.label :検討中,class: 'label'  %>
    <%= form.radio_button :step, '検討中' %>

    <%= form.label :お客様と繋がりませんでした,class: 'label'  %>
    <%= form.radio_button :step, 'お客様と繋がりませんでした' %>

    <%= form.label :契約成立,class: 'label'  %>
    <%= form.radio_button :step, '契約成立' %>

    <%= form.label :報酬振込完了,class: 'label'  %>
    <%= form.radio_button :step, '報酬振込完了' %>
    
  </div>

  
  <div class="actions">
    <%= form.submit '進捗を更新する',data: { confirm: '更新しますか？' },class: 'submit' %>
  </div>
<% end %>

app/views/introductions/index.html.erb
<body class="providerPage">
  <div class="side">
    <%= render '/works/side' %>
  </div>

  <div class="main">

  <%= render '/works/side_header' %>


    <div class="userIndex">
      <h1 class="text-left">口コミ一覧</h1>
      <div class="providerTable">
      <div class="search-form">
        <%= search_form_for @q, url: introductions_index_path do |f| %>
            <%= f.label :name, "進捗度絞り込み",class:"fs-4 " %>
            <%= f.select :step_cont, [['口コミ確認完了'], ['お客様と繋がりませんでした'], ['断られました'], ['検討中'], ['進行中'], ['契約成立'], ['報酬振込完了']], { include_blank: 'すべて' }, { class: "form rounded border border-dark fs-4 w-25" } %>
            <%= f.submit "検索",id:"btn",class:"fs-4 " %>
        <% end %>
        </div>
        <div class="search-form">
        <%= search_form_for @q, url: introductions_index_path do |f| %>
            <%= f.label :name, "キーワード",class:"fs-4" %>
            <%= f.search_field :name_or_user_name_or_work_title_cont,class:"rounded border border-dark fs-4" %>


            <%= f.submit "検索",id:"btn",class:"fs-4 " %>
        <% end %>
      </div>

        <table class="table userTable">
      <tr class="border text-left heading">
      <th>案件名</th><th class="border border-black">紹介者名</th>
      <th class="border border-black">お客様名</th>
      <th class="border border-black">受信日時</th>
      <th class="border border-black">進捗状況</th>
      <th class="border border-black"></th></tr>


      <% @introductions.each do |introduction| %>
        <% if current_provider.email == "tanachu_78@yahoo.co.jp" %>
        <tr class="border text-left">
        <td style=" class="border border-black"><%= introduction.work.title %></td>
        <td style="width:10%" class="border border-black"><%= introduction.user.name %></td>
        <td class="border border-black"><%= introduction.name %></td>
        <td style="width:25%" class=""><%= l introduction.created_at %></td>
        <% if introduction.step == nil %>
          <td style="width:10%" class="border border-black">口コミ完了</td>
          <% else %>
          <td style="width:10%" class="border border-black"><%= introduction.step %></td>
        <% end %>
          <td style="width:8%" class="morebtn  text-center "><a href="<%= introduction.id %>" class="toShow text-decoration-none">詳細</a></td></tr>
        <% elsif introduction.work.provider_id == current_provider.id || introduction.work.id_second == current_provider.email || introduction.work.id_third == current_provider.email  %>
        <tr class="border text-left">
        <td class="border border-black"><%= introduction.work.title %></td>
        <td style="width:10%" class="border border-black"><%= introduction.user.name %></td>
        <td class="border border-black"><%= introduction.name %></td>
        <td style="width:25%" class=""><%= l introduction.created_at %></td>
        <% if introduction.step == nil %>
          <td style="width:10%" class="border border-black">口コミ完了</td>
          <% else %>
          <td style="width:10%" class="border border-black"><%= introduction.step %></td>
        <% end %>
          <td style="width:8%" class="morebtn  text-center "><a href="<%= introduction.id %>" class="toShow text-decoration-none">詳細</a></td></tr>
        <% end %>
      <% end %>


      </table>
      <div class="text-center pagenation">
      <%= paginate @introductions %>
      </div>
      </div>
      </div>

  </div>
</body>

app/views/introductions/new.html.erb
<body class="introduction-new">
<%= render '/layouts/header' %>
  <div class="sign-up-main ">
 <p class="fs-2"><%= alert %></p>
  <% if @introduction.errors.any? %>
  <div id="introductionerror" class="alert">
    <ul>
      <% @introduction.errors.full_messages.each do |message| %>
        <li class="text-center text-white fw-bold fs-4 pb-3">※<%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: [@work, @introduction], local: true ) do |form| %>
  <div class="workTitle">
  案件名: <%= @work.title %>
  </div>
<form>      
  <%= form.text_field :name,class: 'form' , :autocomplete => "off",:class => "feedback-input" , :placeholder => "紹介するお客様名（必須）"  %>
  <%= form.text_field :phonenumber,class: 'form'  , :autocomplete => "off",:class => "feedback-input" ,:placeholder => "紹介するお客様電話番号（必須）" %>
  <%= form.text_area :contents,class: 'form' , :autocomplete => "off",:class => "feedback-input" ,:placeholder => "口コミ内容（任意）" %>
  <div class="checkIntro text-center">案件掲載企業から連絡がいくことを伝えていますか？<%= form.check_box :permission,:as => :boolean, checked:false %></div>
 
  <%= form.submit '口コミする',data: { confirm: '口コミを送信しますか？' },class: 'submit' %>
</form>
<% end %>
</body>
  

app/views/introductions/show.html.erb
<body class="providerPage">
  <div class="side">
    <%= render '/works/side' %>
  </div>
 
  <div class="main">
    <%= render '/works/side_header' %>
    <div class="userIndex">
      <div class="providerTable text-right ">
        <div>
          <button type="button" class="btn btn-primary toNew fs-5 mr-3" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
            ＋ 進捗設定する
          </button>

          <%= form_with(model: @introduction, url: introduction_path, local: true ) do |form| %>  
            <div class="modal w-100 m-auto" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
              <div class="modal-dialog modal-lg">
                <div class="modal-content ">
                  <div class="modal-header">
                     <h5 class="modal-title h4" id="staticBackdropLabel">新規案件作成</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
              
                  <div class="modal-body">
                    <div class="w-75 m-auto mb-4 mt-2 text-left">
                    <%= form.label :進捗編集,class:"h4 text-left" %>
                    <%= form.select :step, [['お客様紹介確認完了'], ['お客様と繋がりませんでした'], ['断られました'],['キャンセル'], ['検討中'], ['進行中'], ['契約成立'], ['報酬振込完了']], {:controller => :introductions, :action => :update, :id => @introduction} %>
                    </div>
                    <div class="w-75 m-auto mb-4 mt-2 text-left">
                    <%= form.label :掲載主からのコメント,class:"h4 text-left" %>
                    <%= form.text_area :comment ,class:"form-control fs-4", size: "20x10" %>                    
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary fs-4" data-bs-dismiss="modal">閉じる</button>
                      <%= form.submit '進捗更新',data: { confirm: '更新しますか？' },class: 'submit btn btn-primary fs-4' %>                 
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
     
     

  <div class="text-center"> 
       <h1 class="text-center mb-5">口コミ内容</h1>

      <table class="table w-75 m-auto">
      
        
      <tr class="border font-bold w-75 m-auto">
        <td class="border border-black  py-3">案件名</td>
        <td class="border border-black text-center"><%= @introduction.work.title %></td>
      </tr>
      <tr class="border">
        <td class="border border-black text-center py-3">紹介者</td>
        <td class="border border-black"><%= @introduction.user.name %>様</td>
      </tr>
      <tr class="border">
        <td class="border border-black text-center py-3">口コミされた方</td>
        <td class="border border-black"><%= @introduction.name %>様</td>
      </tr>
      <tr class="border">
        <td class="border border-black text-center py-3">口コミされた方の電話番号</td>
        <td class="border border-black"><%= @introduction.phonenumber %></td>
      </tr>
      <tr class="border">
        <td class="border border-black text-center py-3">紹介者の口座情報(銀行名/支店/口座種類/口座番号)</td>
        <td class="border border-black"><%= @introduction.user.bank %>/<%= @introduction.user.branch %>/<%= @introduction.user.account_type %>/<%= @introduction.user.account_no %></td>
      </tr>
      
      
      
      <tr class="border">
        <td class="border border-black text-center py-3">口コミの確認</td>
        <td class="border border-black">
        <% if @introduction.permission == true %>
          とっている
          <% elsif @introduction.permission == false %>
          とっていない
          <% end %>
        </td>
      </tr>
      <tr class="border">
        <td class="border border-black text-center py-3">口コミ内容</td>
        <td class="border border-black"><%= @introduction.contents %></td>
      </tr>
      <tr class="border">
        <td class="border border-black text-center py-3">口コミ後の進捗状況</td>
        <% if @introduction.step == nil %>
        <td class="border border-black">口コミ完了</td>
        <% else %>
        <td class="border border-black"><%= @introduction.step %></td>
        <% end %>

      </tr>
      <tr class="border">
        <td class="border border-black text-center py-3">掲載主からのコメント</td>
        <td class="border border-black"><%= @introduction.comment %></td>
      </tr>

    </table>
 
   </div>
      </div>
      </div>

  </div>
</body>