config/routes.rb
Rails.application.routes.draw do


  

  devise_for :providers, controllers: {
    sessions: 'providers/sessions',
    passwords: 'providers/passwords',
    registrations: 'providers/registrations',
    invitations: 'providers/invitations'
  }
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        invitations: 'users/invitations'
      }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get 'registrations/:id/edit_password', to: 'registrations#edit_password', as: 'edit_password'
    put 'registrations/:id/update_password', to: 'registrations#update_password', as: 'update_password'
  end

  devise_scope :provider do
    get '/providers/sign_out' => 'devise/sessions#destroy'
  end

    
  root "tops#index"
  get "tops/index",to:"tops#index"
  get "tops/news",to:"tops#news"
  get "tops/news/:id",to:"tops#newsshow"
  get "tops/policy",to:"tops#policy"
  get "tops/terms",to:"tops#terms"
  get "tops/addprovidercomp",to:"tops#addprovidercomp"
  get "tops/destroycomp",to: "tops#destroycomp"

  resources :works do
    member do
      get :move_top
      get :move_higher
      get :move_lower
      get :move_bottom
    end
    resources :introductions, only: [:create, :edit, :update]
    resources :details, only: [:create]
    resources :work_providers, only: [:create]
  end


  resources :news
  resources :questions
  

  get "posts/index",to:"posts#index"
  get "posts/:id",to:"posts#show"
  get "works/:id/introductions/new", to:"introductions#new"
  get "works/:id/introductions/edit", to:"introductions#edit"
  get "works/:id/work_providers/index", to:"work_providers#index"
  get "works/:id/work_providers/new", to:"work_providers#new"
  post "works/:id/work_providers", to:"work_providers#create"
  get "introductions/complete", to:"introductions#complete"

  get "works/:id/details/new", to:"details#new"

  resources :details

  get "works/:id/introductions", to:"introductions#index"
  get "works/:id/introductions/:id", to:"introductions#show"




  get "introductions/index", to:"introductions#index"
  get "introductions/:id", to:"introductions#show"
  get "introductions/:id/edit", to:"introductions#edit"

  

 resources :introductions do
    resources :progresses, only: [:create, :edit, :update, :show]
  end
  get "introductions/:id/progresses",to:"progresses#new"
  get "progresses/index",to:"progresses#index"
  get "progresses/:id",to:"progresses#show"
  get "progresses/news",to:"progresses#news"

  get "users/index",to:"users#index"
  get "users/:id",to:"users#show"
  
  get "users/complete/:id",to:"users#complete"
  get "users/mypage/:id",to:"users#mypage"
  get "users/destroy/:id",to:"users#destroy"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/posts_controller.rb
class PostsController < WorksController
before_action :authenticate_provider!,except: [:index,:show]
  
  def index　#ユーザー側投稿一覧
    @works = Work.all.page(params[:page]).order(:position)
    @q = Work.ransack(params[:q])
    @works = @q.result(distinct: true).order(:position)
    
  end

  def show　#ユーザー側投稿詳細
     @work = Work.find(params[:id])
     @introduction = Introduction.new
  end
  



end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<body class="post-index">

  <%= render '/layouts/header' %>
  <div class="post-main">
        <h1 class="my-5 text-center">案件一覧</h1>
        <div class="search-form form-inline text-right w-75 m-auto mb-5">
          <%= search_form_for @q, url: posts_index_path  do |f| %>
              <%= f.search_field :title_cont,:class => "form-control  fs-4" , :placeholder => "キーワード" %>

              <%= f.submit "検索",class:"btn btn-primary  fs-4" %>
          <% end %>
        </div>
        <div class="post-list-all">
        <div class="post-list">
          <% @works.each do |work| %>  
            <% if work.status == "公開中" %>
              <section class="card">

                <a  class="link" href="/posts/<%= work.id %>" class=" font-bold">
                  <h1 class="card-title"><%= work.title %></h1>
                  <div class="card-content py-4 px-4 text-left">
                    <p class=" fw-bold text-left">報酬<br><span class="fw-normal "><%= work.reward %></span></p>
                    
                    <p class=" fw-bold text-left">地域<br><span class="fw-normal "><%= work.area %></span></p>
                  </div>
                </a>
              
                <div class="card-link">
                  <a href="/works/<%= work.id %>/introductions/new" class=" font-bold">お客様を紹介する</a>
                  <%= link_to "掲載主に詳細を聞く", "/works/#{ work.id }/details/new"  %> 
                </div>

              </section>
            <% end %>
          <% end %>
     
      </div>  
      </div>
  </div>
  </div>
</body>

app/views/posts/show.html.erb
<body class="post-show">
  <%= render '/layouts/header' %>

<div class="imageList">
<% if @work.images.present? %>
<ul class="slider text-center">
  <% @work.images.each do |img| %>
    <li class="text-center">
      <%= image_tag img.url ,class:"m-auto  text-center"   %>
    </li>
  <% end %>
</ul>
<% end %>
</div>

 
  <div class="postContent ">
    <div class="mb-5">
      <h3 class="pb-3 mb-3">案件名</h3>
      <p><%= @work.title %></p>
    </div>
    <div class="mb-5">
      <h3 class="pb-3 mb-3 ">事業者名</h3>
      <p><%= @work.company_name %></p>
    </div>
    <div class="mb-5">
    <% if @work.link.present? %>
      <h3>事業者ホームページ欄</h3>
      <p><%= auto_link(simple_format(@work.link), html: {target: '_blank'}) %></p>
      <% end %>
    </div>
    <div class="mb-5">
      <h3 class="pb-3 mb-3 ">報酬</h3>
      <p><%= @work.reward %></p>
    </div>
    <div class="mb-5">
      <h3 class="pb-3 mb-3 ">仕事内容</h3>
      <p><%= auto_link(simple_format(@work.pcontent), html: {target: '_blank'}) %></p>
    </div>
    <div class="mb-5">
      <h3 class="pb-3 mb-3 ">報酬支払日</h3>
      <p><%= @work.rday %></p>
    </div>
    <div class="mb-5">
      <h3 class="pb-3 mb-3 ">報酬内容</h3>
      <p><%= simple_format(@work.rcontent) %></p>
    </div>
    <div class="mb-5">
      <h3 class="pb-3 mb-3 ">対象地域</h3>
      <p><%= simple_format(@work.area) %></p>
    </div>
    <div class="mb-5">
      <h3 class="pb-3 mb-3 ">アピールポイント</h3>
      <p><%= simple_format(@work.appeal) %></p>
    </div>

  </div>
<div class="flex  m-auto mt-5">


  <div class="action p-3 mt-4">
  <a href="/works/<%= @work.id %>/details/new" class="text-white text-decoration-none py-2">
    掲載主に詳細を聞く
    </a>
  </div>

  <div class="action p-3 mt-4">
  <a href="/works/<%= @work.id %>/introductions/new" class="text-white text-decoration-none py-2">
    お客様を紹介する
    </a>
  </div>

</div>
  </div>
  </div>


 
</body>